-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 15:33:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sopra-2020WS-team05
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sopra-2020WS-team05
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sopra-2020WS-team05` DEFAULT CHARACTER SET utf8 ;
USE `sopra-2020WS-team05` ;

-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`Profilepicture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`Profilepicture` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`Profilepicture` (
  `picture_id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`picture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`User` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `score` INT NOT NULL DEFAULT 0,
  `highscore` INT NOT NULL,
  `Profilepicture_picture_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `Profilepicture_picture_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_User_Profilepicture1_idx` (`Profilepicture_picture_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Profilepicture1`
    FOREIGN KEY (`Profilepicture_picture_id`)
    REFERENCES `sopra-2020WS-team05`.`Profilepicture` (`picture_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`Item` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`Item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`Achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`Achievement` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`Achievement` (
  `achievement_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`achievement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`User_has_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`User_has_Item` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`User_has_Item` (
  `User_user_id` INT NOT NULL,
  `Item_item_id` INT NOT NULL,
  `anzahl` INT NULL,
  PRIMARY KEY (`User_user_id`, `Item_item_id`),
  INDEX `fk_User_has_Item_Item1_idx` (`Item_item_id` ASC) VISIBLE,
  INDEX `fk_User_has_Item_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Item_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `sopra-2020WS-team05`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Item_Item1`
    FOREIGN KEY (`Item_item_id`)
    REFERENCES `sopra-2020WS-team05`.`Item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`User_has_Achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`User_has_Achievement` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`User_has_Achievement` (
  `User_user_id` INT NOT NULL,
  `Achievement_achievement_id` INT NOT NULL,
  PRIMARY KEY (`User_user_id`, `Achievement_achievement_id`),
  INDEX `fk_User_has_Achievement_Achievement1_idx` (`Achievement_achievement_id` ASC) VISIBLE,
  INDEX `fk_User_has_Achievement_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Achievement_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `sopra-2020WS-team05`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Achievement_Achievement1`
    FOREIGN KEY (`Achievement_achievement_id`)
    REFERENCES `sopra-2020WS-team05`.`Achievement` (`achievement_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sopra-2020WS-team05`.`User_has_User_as_Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sopra-2020WS-team05`.`User_has_User_as_Friend` ;

CREATE TABLE IF NOT EXISTS `sopra-2020WS-team05`.`User_has_User_as_Friend` (
  `User_user_id` INT NOT NULL,
  `User_user_id1` INT NOT NULL,
  PRIMARY KEY (`User_user_id`, `User_user_id1`),
  INDEX `fk_User_has_User_User2_idx` (`User_user_id1` ASC) VISIBLE,
  INDEX `fk_User_has_User_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `sopra-2020WS-team05`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`User_user_id1`)
    REFERENCES `sopra-2020WS-team05`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;